name: Server Build & Push

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker compose -f docker-compose.yml build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry
        run: docker compose -f docker-compose.yml push
      
      - name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GL_SSH_HOST }}
          username: ${{ secrets.GL_SSH_USERNAME }}
          key: ${{ secrets.GL_SSH_SECRET }}
          port: ${{ secrets.GL_SSH_PORT }}
          passphrase: ${{ secrets.GL_SSH_PASSPHRASE }}
          script: |
            docker pull registry.digitalocean.com/trackers/trackers-web:latest
            docker stop trackers-web
            docker rm trackers-web
            docker run --name=trackers-web -d -p 8080:80 registry.digitalocean.com/trackers/trackers-web:latest